/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TargetsTargetIdRouteImport } from './routes/targets.$targetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsTargetIdRoute = TargetsTargetIdRouteImport.update({
  id: '/targets/$targetId',
  path: '/targets/$targetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/targets/$targetId': typeof TargetsTargetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/targets/$targetId': typeof TargetsTargetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/targets/$targetId': typeof TargetsTargetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/targets/$targetId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/targets/$targetId'
  id: '__root__' | '/' | '/targets/$targetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TargetsTargetIdRoute: typeof TargetsTargetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets/$targetId': {
      id: '/targets/$targetId'
      path: '/targets/$targetId'
      fullPath: '/targets/$targetId'
      preLoaderRoute: typeof TargetsTargetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TargetsTargetIdRoute: TargetsTargetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
